package com.panaderia.modelo.negocio;
// Generated 24/07/2021 11:32:47 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * ArticuloPedido generated by hbm2java
 */
public class ArticuloPedido implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -831177287350621694L;
	private int id;
	private CatTipoPan catTipoPan;
	private String folio;
	private BigDecimal cantidad;

	public ArticuloPedido() {
	}

	

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ArticuloPedido other = (ArticuloPedido) obj;
		if (id != other.id)
			return false;
		return true;
	}



	public CatTipoPan getCatTipoPan() {
		return catTipoPan;
	}



	public void setCatTipoPan(CatTipoPan catTipoPan) {
		this.catTipoPan = catTipoPan;
	}

}
