package com.panaderia.modelo.negocio;
// Generated 1/04/2018 10:28:54 AM by Hibernate Tools 4.0.1.Final

/**
 * CatCliente generated by hbm2java
 */
public class CatCliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6270311967492098049L;
	private int id;
	private String descripcion;
	private String telefono;
	private String correo;
	private String direccion;
	private String rfc;

	public CatCliente() {
	}

	public CatCliente(int id, String descripcion) {
		this.id = id;
		this.descripcion = descripcion;
	}

	public CatCliente(int id, String descripcion, String telefono, String correo, String direccion, String rfc) {
		this.id = id;
		this.descripcion = descripcion;
		this.telefono = telefono;
		this.correo = correo;
		this.direccion = direccion;
		this.rfc = rfc;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatCliente other = (CatCliente) obj;
		if (id != other.id)
			return false;
		return true;
	}

}
