package com.panaderia.modelo.negocio;
// Generated 24/07/2021 11:32:47 AM by Hibernate Tools 4.0.1.Final

/**
 * CatEstatusPedido generated by hbm2java
 */
public class CatEstatusPedido implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6533217993428714753L;
	private int id;
	private String descripcion;
	//private Set pedidos = new HashSet(0);

	public CatEstatusPedido() {
	}

	

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatEstatusPedido other = (CatEstatusPedido) obj;
		if (id != other.id)
			return false;
		return true;
	}



	

/*	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}
*/
}
