package com.panaderia.modelo.negocio;

import java.util.HashSet;
import java.util.Set;

// Generated 14/10/2018 11:11:11 AM by Hibernate Tools 4.0.1.Final
/**
 * CatFormula generated by hbm2java
 */
public class CatFormula implements java.io.Serializable {

	private static final long serialVersionUID = -3660459652773986513L;
	private int id;
	private String descripcion;
	//private Set masas = new HashSet(0);

	public CatFormula() {
	}

	public CatFormula(int id, String descripcion) {
		this.id = id;
		this.descripcion = descripcion;
	}

	


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatFormula other = (CatFormula) obj;
		if (id != other.id)
			return false;
		return true;
	}

	

}
