package com.panaderia.modelo.negocio;
// Generated 17/07/2019 12:39:27 PM by Hibernate Tools 4.0.1.Final


/**
 * PanXSucursal generated by hbm2java
 */
public class CatListaInicial implements java.io.Serializable {
	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 186107751834203119L;
	private CatListaInicialId id;
	private int cantidad;
	private String comentario;
	private Integer estatus;

	public CatListaInicial() {
	}

	public CatListaInicialId getId() {
		return id;
	}

	public void setId(CatListaInicialId id) {
		this.id = id;
	}

	public int getCantidad() {
		return cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public String getComentario() {
		return comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Integer getEstatus() {
		return estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	
	

}
