package com.panaderia.modelo.negocio;
// Generated 14/10/2018 11:11:11 AM by Hibernate Tools 4.0.1.Final

/**
 * CatMarca generated by hbm2java
 */
public class CatMarca implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -4221005807534727573L;
	private int id;
	private String descripcion;
	private boolean estatus;
	//private Set catProveedors = new HashSet(0);

	public CatMarca() {
	}

	public CatMarca(int id, String descripcion, boolean estatus) {
		this.id = id;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isEstatus() {
		return this.estatus;
	}

	public void setEstatus(boolean estatus) {
		this.estatus = estatus;
	}

	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatMarca other = (CatMarca) obj;
		if (id != other.id)
			return false;
		return true;
	}

}
