package com.panaderia.modelo.negocio;
// Generated 14/10/2018 11:11:11 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * CatMateriaPrima generated by hbm2java
 */
public class CatMateriaPrima implements java.io.Serializable {

	private static final long serialVersionUID = 4404895454409697386L;
	private int id;
	private CatUbicacion catUbicacion;
	private CatUnidadMedida catUnidadMedida;
	private CatProveedor catProveedor;
	private String descripcion;
	private BigDecimal cantidad;
	private BigDecimal costoKilo;
	private boolean estatus;

	public CatMateriaPrima() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CatUbicacion getCatUbicacion() {
		return this.catUbicacion;
	}

	public void setCatUbicacion(CatUbicacion catUbicacion) {
		this.catUbicacion = catUbicacion;
	}

	public CatUnidadMedida getCatUnidadMedida() {
		return this.catUnidadMedida;
	}

	public void setCatUnidadMedida(CatUnidadMedida catUnidadMedida) {
		this.catUnidadMedida = catUnidadMedida;
	}

	public CatProveedor getCatProveedor() {
		return this.catProveedor;
	}

	public void setCatProveedor(CatProveedor catProveedor) {
		this.catProveedor = catProveedor;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getCostoKilo() {
		return this.costoKilo;
	}

	public void setCostoKilo(BigDecimal costoKilo) {
		this.costoKilo = costoKilo;
	}

	public boolean isEstatus() {
		return this.estatus;
	}

	public void setEstatus(boolean estatus) {
		this.estatus = estatus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatMateriaPrima other = (CatMateriaPrima) obj;
		if (id != other.id)
			return false;
		return true;
	}

}
