package com.panaderia.modelo.negocio;
// Generated 14/10/2018 11:11:11 AM by Hibernate Tools 4.0.1.Final

/**
 * CatProveedor generated by hbm2java
 */
public class CatProveedor implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -2309861553485758426L;
	private int id;
	private CatMarca catMarca;
	private String descripcion;
	private boolean estatus;
	private String rfc;
	private String direccion;
	private String razonSocial;
	private String telefono;
	private String correo;
	//private Set ordenCompraVentas = new HashSet(0);
	//private Set catMateriaPrimas = new HashSet(0);

	public CatProveedor() {
	}

	

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CatMarca getCatMarca() {
		return this.catMarca;
	}

	public void setCatMarca(CatMarca catMarca) {
		this.catMarca = catMarca;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isEstatus() {
		return this.estatus;
	}

	public void setEstatus(boolean estatus) {
		this.estatus = estatus;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatProveedor other = (CatProveedor) obj;
		if (id != other.id)
			return false;
		return true;
	}

}
