package com.panaderia.modelo.negocio;
// Generated 17/07/2019 12:39:27 PM by Hibernate Tools 4.0.1.Final

/**
 * CatTipoPan generated by hbm2java
 */
public class CatTipoPan implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2594736646909864725L;
	private String codigo;
	private String descripcion;
	private double costo;
	private boolean estatus;
	private String comentario;
	private String imagen;
	//private Set panXSucursals = new HashSet(0);
	private String comentaDistribu;

	public String getImagen() {
		return imagen;
	}


	public void setImagen(String imagen) {
		this.imagen = imagen;
	}


	private Integer cantidad=0;
	public CatTipoPan() {
	}
	

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public double getCosto() {
		return this.costo;
	}

	public void setCosto(double costo) {
		this.costo = costo;
	}

	public boolean isEstatus() {
		return this.estatus;
	}

	public void setEstatus(boolean estatus) {
		this.estatus = estatus;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codigo == null) ? 0 : codigo.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatTipoPan other = (CatTipoPan) obj;
		if (codigo == null) {
			if (other.codigo != null)
				return false;
		} else if (!codigo.equals(other.codigo))
			return false;
		return true;
	}


	public Integer getCantidad() {
		return cantidad;
	}


	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}


	public String getComentaDistribu() {
		return comentaDistribu;
	}


	public void setComentaDistribu(String comentaDistribu) {
		this.comentaDistribu = comentaDistribu;
	}

	
	/*public Set getPanXSucursals() {
		return this.panXSucursals;
	}

	public void setPanXSucursals(Set panXSucursals) {
		this.panXSucursals = panXSucursals;
	}*/

}
