package com.panaderia.modelo.negocio;
// Generated 14/10/2018 11:11:11 AM by Hibernate Tools 4.0.1.Final

/**
 * CatUbicacion generated by hbm2java
 */
public class CatUbicacion implements java.io.Serializable {

	
	private static final long serialVersionUID = 5375143262792032602L;
	private int id;
	private String descripcion;
	private Boolean estatus;
	//private Set catMateriaPrimas = new HashSet(0);

	public CatUbicacion() {
	}

	public CatUbicacion(int id, String descripcion) {
		this.id = id;
		this.descripcion = descripcion;
	}

	

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}

	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatUbicacion other = (CatUbicacion) obj;
		if (id != other.id)
			return false;
		return true;
	}

}
