package com.panaderia.modelo.negocio;
// Generated 14/10/2018 11:11:11 AM by Hibernate Tools 4.0.1.Final

/**
 * CatUnidadMedida generated by hbm2java
 */
public class CatUnidadMedida implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4712440770404790770L;
	private int id;
	private String descripcion;
	private String abreviatura;
	private boolean estatus;
	// private Set catMateriaPrimas = new HashSet(0);

	public CatUnidadMedida() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isEstatus() {
		return this.estatus;
	}

	public void setEstatus(boolean estatus) {
		this.estatus = estatus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatUnidadMedida other = (CatUnidadMedida) obj;
		if (id != other.id)
			return false;
		return true;
	}

	public String getAbreviatura() {
		return abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

}
