package com.panaderia.modelo.negocio;
// Generated 14/10/2018 11:11:11 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Masa generated by hbm2java
 */
public class Masa implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -2657911526653970552L;
	private int id;
	private CatFormula catFormula;
	private BigDecimal gramos;
	private Date fechaElaboracion;
	private int piezas;

	public Masa() {
	}

	

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CatFormula getCatFormula() {
		return this.catFormula;
	}

	public void setCatFormula(CatFormula catFormula) {
		this.catFormula = catFormula;
	}

	public BigDecimal getGramos() {
		return this.gramos;
	}

	public void setGramos(BigDecimal gramos) {
		this.gramos = gramos;
	}

	public Date getFechaElaboracion() {
		return this.fechaElaboracion;
	}

	public void setFechaElaboracion(Date fechaElaboracion) {
		this.fechaElaboracion = fechaElaboracion;
	}

	public int getPiezas() {
		return this.piezas;
	}

	public void setPiezas(int piezas) {
		this.piezas = piezas;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Masa other = (Masa) obj;
		if (id != other.id)
			return false;
		return true;
	}

}
