package com.panaderia.modelo.negocio;
// Generated 14/10/2018 11:11:11 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * MateriaFormula generated by hbm2java
 */
public class MateriaFormula implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -672112881872127509L;
	private MateriaFormulaId id;
	private BigDecimal cantidadMatPrima;
	private String unidadMedidaDes;

	public MateriaFormula() {
	}



	public MateriaFormulaId getId() {
		return this.id;
	}

	public void setId(MateriaFormulaId id) {
		this.id = id;
	}

	public BigDecimal getCantidadMatPrima() {
		return this.cantidadMatPrima;
	}

	public void setCantidadMatPrima(BigDecimal cantidadMatPrima) {
		this.cantidadMatPrima = cantidadMatPrima;
	}

	public String getUnidadMedidaDes() {
		return unidadMedidaDes;
	}

	public void setUnidadMedidaDes(String unidadMedidaDes) {
		this.unidadMedidaDes = unidadMedidaDes;
	}

}
