package com.panaderia.modelo.negocio;
// Generated 14/10/2018 11:11:11 AM by Hibernate Tools 4.0.1.Final

/**
 * MateriaFormulaId generated by hbm2java
 */
public class MateriaFormulaId implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 186631477573894991L;
	private int idMateria;
	private int idFormula;

	public MateriaFormulaId() {
	}

	

	public int getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(int idMateria) {
		this.idMateria = idMateria;
	}

	public int getIdFormula() {
		return this.idFormula;
	}

	public void setIdFormula(int idFormula) {
		this.idFormula = idFormula;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MateriaFormulaId))
			return false;
		MateriaFormulaId castOther = (MateriaFormulaId) other;

		return (this.getIdMateria() == castOther.getIdMateria()) && (this.getIdFormula() == castOther.getIdFormula());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMateria();
		result = 37 * result + this.getIdFormula();
		return result;
	}

}
