package com.panaderia.modelo.negocio;
// Generated 14/10/2018 11:11:11 AM by Hibernate Tools 4.0.1.Final

/**
 * MatPrimaOrdenId generated by hbm2java
 */
public class MatPrimaOrdenId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5954467954106962690L;
	private String folioOrden;
	private int idMateria;

	public MatPrimaOrdenId() {
	}

	public MatPrimaOrdenId(String folioOrden, int idMateria) {
		this.folioOrden = folioOrden;
		this.idMateria = idMateria;
	}

	public String getFolioOrden() {
		return this.folioOrden;
	}

	public void setFolioOrden(String folioOrden) {
		this.folioOrden = folioOrden;
	}

	public int getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(int idMateria) {
		this.idMateria = idMateria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatPrimaOrdenId))
			return false;
		MatPrimaOrdenId castOther = (MatPrimaOrdenId) other;

		return ((this.getFolioOrden() == castOther.getFolioOrden()) || (this.getFolioOrden() != null
				&& castOther.getFolioOrden() != null && this.getFolioOrden().equals(castOther.getFolioOrden())))
				&& (this.getIdMateria() == castOther.getIdMateria());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFolioOrden() == null ? 0 : this.getFolioOrden().hashCode());
		result = 37 * result + this.getIdMateria();
		return result;
	}

}
