package com.panaderia.modelo.negocio;
// Generated 14/10/2018 11:11:11 AM by Hibernate Tools 4.0.1.Final

/**
 * MatPrimaOrden generated by hbm2java
 */
public class MatPrimaOrden implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7898969745003315751L;
	private MatPrimaOrdenId id;
	private int cantidad;

	public MatPrimaOrden() {
	}

	

	public MatPrimaOrdenId getId() {
		return this.id;
	}

	public void setId(MatPrimaOrdenId id) {
		this.id = id;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
