package com.panaderia.modelo.negocio;
// Generated 14/10/2018 11:11:11 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * OrdenCompraVenta generated by hbm2java
 */
public class OrdenCompraVenta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1662700615930050766L;
	private String folio;
	private CatProveedor catProveedor;
	private CatUsuario catUsuario;
	private Date fechaP;
	private Date fechaE;
	private String sucursal;
	private String recibio;
	private Character tipo;

	public OrdenCompraVenta() {
	}

	

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public CatProveedor getCatProveedor() {
		return this.catProveedor;
	}

	public void setCatProveedor(CatProveedor catProveedor) {
		this.catProveedor = catProveedor;
	}

	public CatUsuario getCatUsuario() {
		return this.catUsuario;
	}

	public void setCatUsuario(CatUsuario catUsuario) {
		this.catUsuario = catUsuario;
	}

	public Date getFechaP() {
		return this.fechaP;
	}

	public void setFechaP(Date fechaP) {
		this.fechaP = fechaP;
	}

	public Date getFechaE() {
		return this.fechaE;
	}

	public void setFechaE(Date fechaE) {
		this.fechaE = fechaE;
	}

	public String getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(String sucursal) {
		this.sucursal = sucursal;
	}

	public String getRecibio() {
		return this.recibio;
	}

	public void setRecibio(String recibio) {
		this.recibio = recibio;
	}

	public Character getTipo() {
		return this.tipo;
	}

	public void setTipo(Character tipo) {
		this.tipo = tipo;
	}

}
