package com.panaderia.modelo.negocio;
// Generated 17/07/2019 12:39:27 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * PanXSucursal generated by hbm2java
 */
public class PanXSucursal implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -6117085735524607792L;
	private PanXSucursalId id;
	private CatTipoPan catTipoPan;
	private CatUbicacion catUbicacion;
	private int cantidad;
	private String entrega;
	private String recibe;
	
	
	private String comentario;
	private String comentarioRecibe;
	private Integer estatus;
	//cantidad de tipo de pan por dia
	private int cantidadTPXDia;
	
	private int corteMatutino;
	private int corteVespertino;
	
	private BigDecimal cantidadTemp;
	
	//no esta mapeado
	private float cantVenta;
	
	private String codigoRepetido;

	public PanXSucursal() {
	}

	public PanXSucursalId getId() {
		return this.id;
	}

	public void setId(PanXSucursalId id) {
		this.id = id;
	}

	public CatTipoPan getCatTipoPan() {
		return this.catTipoPan;
	}

	public void setCatTipoPan(CatTipoPan catTipoPan) {
		this.catTipoPan = catTipoPan;
	}

	public CatUbicacion getCatUbicacion() {
		return this.catUbicacion;
	}

	public void setCatUbicacion(CatUbicacion catUbicacion) {
		this.catUbicacion = catUbicacion;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public String getEntrega() {
		return this.entrega;
	}

	public void setEntrega(String entrega) {
		this.entrega = entrega;
	}

	public String getRecibe() {
		return this.recibe;
	}

	public void setRecibe(String recibe) {
		this.recibe = recibe;
	}

	

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PanXSucursal other = (PanXSucursal) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	public String getComentarioRecibe() {
		return comentarioRecibe;
	}

	public void setComentarioRecibe(String comentarioRecibe) {
		this.comentarioRecibe = comentarioRecibe;
	}

	public Integer getEstatus() {
		return estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	public float getCantVenta() {
		return cantVenta;
	}

	public void setCantVenta(float cantVenta) {
		this.cantVenta = cantVenta;
	}

	public String getCodigoRepetido() {
		return codigoRepetido;
	}

	public void setCodigoRepetido(String codigoRepetido) {
		this.codigoRepetido = codigoRepetido;
	}

	public int getCantidadTPXDia() {
		return cantidadTPXDia;
	}

	public void setCantidadTPXDia(int cantidadTPXDia) {
		this.cantidadTPXDia = cantidadTPXDia;
	}

	public int getCorteMatutino() {
		return corteMatutino;
	}

	public void setCorteMatutino(int corteMatutino) {
		this.corteMatutino = corteMatutino;
	}

	public int getCorteVespertino() {
		return corteVespertino;
	}

	public void setCorteVespertino(int corteVespertino) {
		this.corteVespertino = corteVespertino;
	}

	public BigDecimal getCantidadTemp() {
		return cantidadTemp;
	}

	public void setCantidadTemp(BigDecimal cantidadTemp) {
		this.cantidadTemp = cantidadTemp;
	}

	
	

}
