package com.panaderia.modelo.negocio;
// Generated 17/07/2019 12:39:27 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * PanXSucursalId generated by hbm2java
 */
public class PanXSucursalId implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -40995445619720015L;
	private String codigopan;
	private int idUbicacion;
	private Date fecha;
	private int tipo;

	public PanXSucursalId() {
	}

	public String getCodigopan() {
		return this.codigopan;
	}

	public void setCodigopan(String codigopan) {
		this.codigopan = codigopan;
	}

	public int getIdUbicacion() {
		return this.idUbicacion;
	}

	public void setIdUbicacion(int idUbicacion) {
		this.idUbicacion = idUbicacion;
	}
	
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
	
	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codigopan == null) ? 0 : codigopan.hashCode());
		result = prime * result + ((fecha == null) ? 0 : fecha.hashCode());
		result = prime * result + idUbicacion;
		result = prime * result + tipo;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PanXSucursalId other = (PanXSucursalId) obj;
		if (codigopan == null) {
			if (other.codigopan != null)
				return false;
		} else if (!codigopan.equals(other.codigopan))
			return false;
		if (fecha == null) {
			if (other.fecha != null)
				return false;
		} else if (!fecha.equals(other.fecha))
			return false;
		if (idUbicacion != other.idUbicacion)
			return false;
		if (tipo != other.tipo)
			return false;
		return true;
	}
	
}
