package com.panaderia.modelo.negocio;
// Generated 24/07/2021 11:32:47 AM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6287816630754899377L;
	private String folio;
	private CatEstatusPedido catEstatusPedido;
	private CatCliente catCliente;
	private String nombre;
	private String ape1;
	private String ape2;
	private String domicilio;
	private Date fecInicio;
	private Date fecFin;
	private String telefono;
	private BigDecimal total;
	private BigDecimal ACuenta;
	private Integer anio;
	private String comentario;
	
	private String horaI;
	private String horaF;
	private String coordenada;

	public Pedido() {
	}

	

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public CatEstatusPedido getCatEstatusPedido() {
		return this.catEstatusPedido;
	}

	public void setCatEstatusPedido(CatEstatusPedido catEstatusPedido) {
		this.catEstatusPedido = catEstatusPedido;
	}

	public CatCliente getCatCliente() {
		return this.catCliente;
	}

	public void setCatCliente(CatCliente catCliente) {
		this.catCliente = catCliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApe1() {
		return this.ape1;
	}

	public void setApe1(String ape1) {
		this.ape1 = ape1;
	}

	public String getApe2() {
		return this.ape2;
	}

	public void setApe2(String ape2) {
		this.ape2 = ape2;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}
	

	public Date getFecInicio() {
		return this.fecInicio;
	}

	public void setFecInicio(Date fecInicio) {
		this.fecInicio = fecInicio;
	}

	public Date getFecFin() {
		return this.fecFin;
	}

	public void setFecFin(Date fecFin) {
		this.fecFin = fecFin;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public BigDecimal getACuenta() {
		return this.ACuenta;
	}

	public void setACuenta(BigDecimal ACuenta) {
		this.ACuenta = ACuenta;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((folio == null) ? 0 : folio.hashCode());
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pedido other = (Pedido) obj;
		if (folio == null) {
			if (other.folio != null)
				return false;
		} else if (!folio.equals(other.folio))
			return false;
		return true;
	}



	public Integer getAnio() {
		return anio;
	}



	public void setAnio(Integer anio) {
		this.anio = anio;
	}



	public String getComentario() {
		return comentario;
	}



	public void setComentario(String comentario) {
		this.comentario = comentario;
	}



	public String getHoraI() {
		return horaI;
	}



	public void setHoraI(String horaI) {
		this.horaI = horaI;
	}



	public String getHoraF() {
		return horaF;
	}



	public void setHoraF(String horaF) {
		this.horaF = horaF;
	}



	public String getCoordenada() {
		return coordenada;
	}



	public void setCoordenada(String coordenada) {
		this.coordenada = coordenada;
	}

}
