package com.panaderia.modelo.negocio;

import java.math.BigDecimal;

// Generated 14/06/2024 01:01:41 PM by Hibernate Tools 5.3.0.Beta2

/**
 * PrecioCantidadSucursal generated by hbm2java
 */
public class PrecioCantidadSucursal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6586186282534177550L;
	private PrecioCantidadSucursalId id;
	private CatUbicacion catUbicacion;
	private Integer cantidad;
	private Integer cantidadVendida;
	private Integer estatus;
	private BigDecimal cantidadTemp;
	
	

	public PrecioCantidadSucursal() {
		
	}

	public PrecioCantidadSucursalId getId() {
		return this.id;
	}

	public void setId(PrecioCantidadSucursalId id) {
		this.id = id;
	}

	public CatUbicacion getCatUbicacion() {
		return this.catUbicacion;
	}

	public void setCatUbicacion(CatUbicacion catUbicacion) {
		this.catUbicacion = catUbicacion;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public Integer getCantidadVendida() {
		return this.cantidadVendida;
	}

	public void setCantidadVendida(Integer cantidadVendida) {
		this.cantidadVendida = cantidadVendida;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PrecioCantidadSucursal other = (PrecioCantidadSucursal) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	public Integer getEstatus() {
		return estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	public BigDecimal getCantidadTemp() {
		return cantidadTemp;
	}

	public void setCantidadTemp(BigDecimal cantidadTemp) {
		this.cantidadTemp = cantidadTemp;
	}

}
