package com.panaderia.modelo.negocio;
// Generated 14/06/2024 01:01:41 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * PrecioCantidadSucursalId generated by hbm2java
 */
public class PrecioCantidadSucursalId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4731674224861235133L;
	private double costo;
	private int idUbicacion;
	private Date fecha;

	public PrecioCantidadSucursalId() {
	}

	

	public int getIdUbicacion() {
		return this.idUbicacion;
	}

	public void setIdUbicacion(int idUbicacion) {
		this.idUbicacion = idUbicacion;
	}

	
	public double getCosto() {
		return costo;
	}



	public void setCosto(double costo) {
		this.costo = costo;
	}



	public Date getFecha() {
		return fecha;
	}



	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(costo);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + ((fecha == null) ? 0 : fecha.hashCode());
		result = prime * result + idUbicacion;
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PrecioCantidadSucursalId other = (PrecioCantidadSucursalId) obj;
		if (Double.doubleToLongBits(costo) != Double.doubleToLongBits(other.costo))
			return false;
		if (fecha == null) {
			if (other.fecha != null)
				return false;
		} else if (!fecha.equals(other.fecha))
			return false;
		if (idUbicacion != other.idUbicacion)
			return false;
		return true;
	}


}
