package com.panaderia.modelo.negocio;
// Generated 14/06/2024 01:42:27 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * PrecioCantidadVenta generated by hbm2java
 */
public class PrecioCantidadVenta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3442916529015053722L;
	private PrecioCantidadVentaId id;
	private Integer cantidad;
	private Date fecha;
	private Integer idUsuario;
	private Integer idUbicacion;
	private Integer estatus;
	private Integer consecutivo;

	public PrecioCantidadVenta() {
	}

	public PrecioCantidadVenta(PrecioCantidadVentaId id) {
		this.id = id;
	}


	public PrecioCantidadVentaId getId() {
		return this.id;
	}

	public void setId(PrecioCantidadVentaId id) {
		this.id = id;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Integer getIdUbicacion() {
		return this.idUbicacion;
	}

	public void setIdUbicacion(Integer idUbicacion) {
		this.idUbicacion = idUbicacion;
	}

	public Integer getEstatus() {
		return estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	public Integer getConsecutivo() {
		return consecutivo;
	}

	public void setConsecutivo(Integer consecutivo) {
		this.consecutivo = consecutivo;
	}

}
