package com.panaderia.modelo.negocio;
// Generated 14/06/2024 01:42:27 PM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;

/**
 * PrecioCantidadVentaId generated by hbm2java
 */
public class PrecioCantidadVentaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4816956038397009032L;
	private String folio;
	private double costo;

	public PrecioCantidadVentaId() {
		
	}


	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public double getCosto() {
		return costo;
	}


	public void setCosto(double costo) {
		this.costo = costo;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(costo);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + ((folio == null) ? 0 : folio.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PrecioCantidadVentaId other = (PrecioCantidadVentaId) obj;
		if (Double.doubleToLongBits(costo) != Double.doubleToLongBits(other.costo))
			return false;
		if (folio == null) {
			if (other.folio != null)
				return false;
		} else if (!folio.equals(other.folio))
			return false;
		return true;
	}

}
