package com.panaderia.modelo.negocio;
// Generated 4/11/2019 09:18:39 PM by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import com.panaderia.modelo.negocio.CatTipoPan;
import com.panaderia.modelo.negocio.CatUbicacion;
import com.panaderia.modelo.negocio.CatUsuario;
import com.panaderia.modelo.negocio.RegistroVentaId;

/**
 * RegistroVenta generated by hbm2java
 */
public class RegistroVenta implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -6199178198473930316L;
	private RegistroVentaId id;
	private CatTipoPan catTipoPan;
	private CatUbicacion catUbicacion;
	private CatUsuario catUsuario;
	private int cantidad;
	private Date fecha;
	private Character estatus;
	private int consecutivo;
	
	private Integer formaPago;
	private BigDecimal acuenta;
	private BigDecimal descuento;
	
	//para articulos igualacion
	private int tipo;
	private BigDecimal precio;
	private BigDecimal listrosIgualacion;
	
	private BigDecimal efectivo;
	private BigDecimal total;

	public RegistroVenta() {
	}

	
	public RegistroVentaId getId() {
		return this.id;
	}

	public void setId(RegistroVentaId id) {
		this.id = id;
	}

	public CatTipoPan getCatTipoPan() {
		return this.catTipoPan;
	}

	public void setCatTipoPan(CatTipoPan catTipoPan) {
		this.catTipoPan = catTipoPan;
	}

	public CatUbicacion getCatUbicacion() {
		return this.catUbicacion;
	}

	public void setCatUbicacion(CatUbicacion catUbicacion) {
		this.catUbicacion = catUbicacion;
	}

	public CatUsuario getCatUsuario() {
		return this.catUsuario;
	}

	public void setCatUsuario(CatUsuario catUsuario) {
		this.catUsuario = catUsuario;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Character getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Character estatus) {
		this.estatus = estatus;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}
	
	public Integer getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(Integer formaPago) {
		this.formaPago = formaPago;
	}

	public BigDecimal getAcuenta() {
		return this.acuenta;
	}

	public void setAcuenta(BigDecimal acuenta) {
		this.acuenta = acuenta;
	}

	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

	public int getTipo() {
		return tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	public BigDecimal getPrecio() {
		return precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public BigDecimal getListrosIgualacion() {
		return listrosIgualacion;
	}

	public void setListrosIgualacion(BigDecimal listrosIgualacion) {
		this.listrosIgualacion = listrosIgualacion;
	}

	public BigDecimal getEfectivo() {
		return efectivo;
	}

	public void setEfectivo(BigDecimal efectivo) {
		this.efectivo = efectivo;
	}

	public BigDecimal getTotal() {
		return total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}
}
