package com.panaderia.modelo.negocio;
// Generated 5/11/2019 11:36:02 PM by Hibernate Tools 4.0.1.Final

/**
 * RegistroVentaId generated by hbm2java
 */
public class RegistroVentaId implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4187436157329162173L;
	private String folio;
	private String codigoTipoPan;

	public RegistroVentaId() {
	}

	public RegistroVentaId(String folio, String codigoTipoPan) {
		this.folio = folio;
		this.codigoTipoPan = codigoTipoPan;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public String getCodigoTipoPan() {
		return this.codigoTipoPan;
	}

	public void setCodigoTipoPan(String codigoTipoPan) {
		this.codigoTipoPan = codigoTipoPan;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codigoTipoPan == null) ? 0 : codigoTipoPan.hashCode());
		result = prime * result + ((folio == null) ? 0 : folio.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RegistroVentaId other = (RegistroVentaId) obj;
		if (codigoTipoPan == null) {
			if (other.codigoTipoPan != null)
				return false;
		} else if (!codigoTipoPan.equals(other.codigoTipoPan))
			return false;
		if (folio == null) {
			if (other.folio != null)
				return false;
		} else if (!folio.equals(other.folio))
			return false;
		return true;
	}

}
